name: Dockerize

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer QEMU (pour la compatibilité multiplateforme)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Étape 3 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 4 : Se connecter à DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 5 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: rwinsee/app_shiny_romeo:latest
